In [1]:
import pandas as pd

In [2]:
result1 = pd.read_csv('result_mutiple1-1.csv', header=0, encoding='utf-8')
result1

,Feature,Model Args,Test Acc
0,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.446053
1,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.377851
2,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.513816
3,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.475219
4,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.411842
...,...,...,...
76,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.462745
77,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.603922
78,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745
79,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745
80,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.539216

In [3]:
result2 = pd.read_csv('result_mutiple1.csv', header=0, encoding='utf-8')
result2

,Feature,Model Args,Test Acc
0,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.562719
1,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.540570
2,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.570176
3,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.565570
4,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.561184
...,...,...,...
76,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.511765
77,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.549020
78,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.568627
79,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.554902
80,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.584314

In [4]:
result3 = pd.read_csv('result_mutiple2.csv', header=0, encoding='utf-8')
result3

,Feature,Model Args,Test Acc
0,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.563597
1,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.540351
2,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.569079
3,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.571272
4,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.562062
...,...,...,...
76,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.511765
77,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.543137
78,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.566667
79,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.556863
80,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.586275

In [5]:
result4 = pd.read_csv('result_mutiple2-1.csv', header=0, encoding='utf-8')
result4

,Feature,Model Args,Test Acc
0,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.207237
1,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.207675
2,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.319298
3,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.207456
4,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.203509
...,...,...,...
76,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.462745
77,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.462745
78,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745
79,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745
80,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745

In [6]:
result = pd.concat([result1, result2], axis=0)
result = pd.concat([result, result3], axis=0)
result = pd.concat([result, result4], axis=0)
result

,Feature,Model Args,Test Acc
0,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.446053
1,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.377851
2,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 100 ...,0.513816
3,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.475219
4,chameleon-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.411842
...,...,...,...
76,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.462745
77,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 200 ...,0.462745
78,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745
79,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745
80,wisconsin-unmodified,--model gcn --hidden1 64 --early_stopping 40 ...,0.462745

In [7]:
result = result.sort_values(by=['Feature', 'Model Args'])

In [8]:
result.to_csv('result_mutiple_all.csv', header=True, index=False)